ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    environments:
      - staging
      - prod
    cli_version: v0.5.0-rc.0
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    builds:
      - name: image
        workflow: .github/workflows/build-image.yaml
        triggers: []
        state_tags:
          - image_digest
        matrix:
          dimensions:
            arch:
              - amd64
              - arm64
            os:
              - linux
          max_parallel: 2
          fail_fast: false
        artifact:
          upload: dist/**
      - name: bundle
        workflow: .github/workflows/build-bundle.yaml
        triggers: []
        artifact:
          downloads:
            - image
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
    publish:
      workflow: .github/workflows/publish.yaml
    dispatch_inputs:
      force:
        type: boolean
        default: false
        description: Force re-promote
      reason:
        type: string
        description: Operator note for this manual run
    pr_preview:
      enabled: true
      comment: true
    environment_config:
      prod:
        gha_environment: prod
  state:
    staging:
      sha: 3cd05bbd401553bebf4c4523608883a92e0db572
      version: v0.1.0-rc.0
      committed_at: "2026-06-25T06:53:32Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: 3cd05bbd401553bebf4c4523608883a92e0db572
          deployed_at: "2026-06-25T06:53:32Z"
          deployed_by: joshua-temple
      builds:
        image:
          sha: 3cd05bbd401553bebf4c4523608883a92e0db572
          artifact_id: image-linux-amd64
        bundle:
          sha: 3cd05bbd401553bebf4c4523608883a92e0db572
          artifact_id: bundle-3cd05bbd401553bebf4c4523608883a92e0db572
