ci:
  config:
    schema_version: 1
    trunk_branch: main
    triggers:
      - src/**
    environments:
      - staging
      - prod
    cli_version: v0.5.0-rc.0
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    builds:
      - name: image
        workflow: .github/workflows/build-image.yaml
        triggers: []
        state_tags:
          - image_digest
        matrix:
          dimensions:
            arch:
              - amd64
              - arm64
            os:
              - linux
          max_parallel: 2
          fail_fast: false
        artifact:
          upload: dist/**
      - name: bundle
        workflow: .github/workflows/build-bundle.yaml
        triggers: []
        artifact:
          downloads:
            - image
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
    publish:
      workflow: .github/workflows/publish.yaml
    dispatch_inputs:
      force:
        type: boolean
        default: false
        description: Force re-promote
      reason:
        type: string
        description: Operator note for this manual run
    pr_preview:
      enabled: true
      comment: true
    environment_config:
      prod:
        gha_environment: prod
  state:
    prod: {}
    release:
      sha: a09a40b1152a68c31af078ecd16d6201c21a4566
      version: v0.1.0
      committed_at: "2026-06-25T03:35:27Z"
      committed_by: github-actions[bot]
    staging:
      sha: 008341189217a00b548cc2b8a8588c6a6ed36149
      version: v0.1.0-rc.1
      committed_at: "2026-06-25T03:37:24Z"
      committed_by: joshua-temple
      builds:
        bundle:
          sha: 008341189217a00b548cc2b8a8588c6a6ed36149
          artifact_id: bundle-008341189217a00b548cc2b8a8588c6a6ed36149
        image:
          sha: 008341189217a00b548cc2b8a8588c6a6ed36149
          artifact_id: image-linux-amd64
      deploys:
        app:
          sha: 008341189217a00b548cc2b8a8588c6a6ed36149
          deployed_at: "2026-06-25T03:37:24Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: a09a40b1152a68c31af078ecd16d6201c21a4566
    released_on: "2026-06-25T03:35:27Z"
    released_by: github-actions[bot]
